services:
  backend:
    image: beershop-backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/code
      - ./.env:/code/.env
      - ./backend/pyproject.toml:/opt/pysetup/pyproject.toml
      - ./backend/poetry.lock:/opt/pysetup/poetry.lock
    env_file:
      - .env
    command: fastapi dev main.py --app=app --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"

  frontend:
    image: beershop-frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
    command: npm run dev
    depends_on:
      - backend