FROM node:20-alpine

WORKDIR /code

# Copy package.json and package-lock.json to the working directory
COPY frontend/package*.json .

# Install any needed packages specified in package.json
RUN npm install